- name: Create Azure VM
  hosts: localhost
  connection: local
  tasks:
  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: myResourceGroup
      name: myVM
      vm_size: Standard_DS1_v2
      admin_username: oaker
      ssh_password_enabled: false
      image:
        offer: CentOS
        publisher: OpenLogic
        sku: '7.5'
        version: latest
